---
version: 3
hotkeys:
  toggle-window:
    - Ctrl-Space
  copy:
    - ⌘-C
  paste:
    - ⌘-V
  home:
    - ⌘-Left
    - Home
  end:
    - ⌘-Right
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-next-word:
    - ⌥-Delete
  clear:
    - ⌘-K
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  ctrl-c:
    - Ctrl-C
  copy-current-path: []
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  scroll-to-bottom: []
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings:
    - ⌘-,
  settings-tab: {}
  serial:
    - Alt-K
  restart-serial-session: []
  new-window:
    - ⌘-N
  new-tab:
    - ⌘-T
  workspace-profile-1: []
  workspace-profile-2: []
  workspace-profile-3: []
  workspace-profile-4: []
  workspace-profile-5: []
  profile-selector:
    - ⌘-E
  toggle-fullscreen:
    - Ctrl+⌘+F
  rename-tab:
    - ⌘-R
  close-tab:
    - ⌘-W
  reopen-tab:
    - ⌘-Shift-T
  toggle-last-tab: []
  next-tab:
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Tab
  move-tab-left:
    - ⌘-Shift-Left
  move-tab-right:
    - ⌘-Shift-Right
  rearrange-panes:
    - ⌘-Shift
  duplicate-tab: []
  explode-tab:
    - ⌘-Shift-.
  combine-tabs:
    - ⌘-Shift-,
  tab-1:
    - ⌘-1
  tab-2:
    - ⌘-2
  tab-3:
    - ⌘-3
  tab-4:
    - ⌘-4
  tab-5:
    - ⌘-5
  tab-6:
    - ⌘-6
  tab-7:
    - ⌘-7
  tab-8:
    - ⌘-8
  tab-9:
    - ⌘-9
  tab-10:
    - ⌘-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - ⌘-Shift-D
  split-bottom:
    - ⌘-D
  split-left: []
  split-top: []
  pane-maximize:
    - ⌘-⌥-Enter
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  switch-profile:
    - ⌘-Shift-E
  close-pane:
    - ⌘-Shift-W
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  profile: {}
  profile-selectors: {}
  select-all:
    - ⌘-A
terminal:
  searchOptions: {}
  colorScheme:
    name: Betelgeuse
    foreground: '#eceff1'
    background: '#161925'
    selection: null
    cursor: '#FFCC00'
    cursorAccent: null
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - rgba(255, 255, 255, 0.2)
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  customColorSchemes: []
  autoOpen: true
  scrollbackLines: 100000
  frontend: xterm-webgl
  font: Hack Nerd Font
  ligatures: true
  background: colorScheme
  showTabProfileIcon: true
ssh:
  warnOnClose: true
configSync:
  parts: {}
  token: XXX
clickableLinks:
  modifier: metaKey
workspaceManager: {}
accessibility: {}
appearance:
  flexTabs: true
  frame: full
hacks: {}
pluginBlacklist: []
profileDefaults: {}
profiles: []
enableAnalytics: false
enableWelcomeTab: false
