---
# The original .chezmoidata.yaml was moved one directory up to software.yml
colors:
  color1: #000AAA
  color2: #000AAA
  color3: #000AAA
  color4: #000AAA
  color5: #000AAA
  color6: #000AAA
  color7: #000AAA
  color8: #000AAA
  color9: #000AAA
  color10: #000AAA
  color11: #000AAA
  color12: #000AAA
  color13: #000AAA
  color14: #000AAA
config:
  gpg: https://raw.githubusercontent.com/drduh/config/master/gpg.conf
softwarePlugins:
  vim:
    plugins:
      - https://github.com/dense-analysis/ale.git
      - https://github.com/pearofducks/ansible-vim.git
      - https://github.com/neoclide/coc.nvim.git
      - https://github.com/ekalinin/dockerfile.vim.git
      - https://github.com/editorconfig/editorconfig-vim.git
      - https://github.com/junegunn/fzf.git
      - https://github.com/junegunn/fzf.vim.git
      - https://github.com/itchyny/lightline.vim.git
      - https://github.com/scrooloose/nerdtree.git
      - https://github.com/stanangeloff/php.vim.git
      - https://github.com/hdima/python-syntax.git
      - https://github.com/vim-syntastic/syntastic.git
      - https://github.com/vim-airline/vim-airline.git
      - https://github.com/kristijanhusak/vim-carbon-now-sh.git
      - https://github.com/ryanoasis/vim-devicons.git
      - https://github.com/tpope/vim-fugitive.git
      - https://github.com/airblade/vim-gitgutter.git
      - https://github.com/fatih/vim-go.git
      - https://github.com/pangloss/vim-javascript.git
      - https://github.com/mxw/vim-jsx.git
      - https://github.com/plasticboy/vim-markdown.git
      - https://github.com/terryma/vim-multiple-cursors.git
      - https://github.com/prettier/vim-prettier.git
      - https://github.com/tpope/vim-sensible.git
      - https://github.com/tpope/vim-surround.git
      - https://github.com/nanotee/zoxide.vim.git
