---
colors:
  background: '#161925'
  color0: '#161925'
  color1: '#282C34'
  color2: '#ED254E'
  color3: '#71F79F'
  color4: '#F9DC5C'
  color5: '#7CB7FF'
  color6: '#C74D89'
  color7: '#00C1E4'
  color8: '#DCDFE4'
  color9: '#4C5058'
  color10: '#FF4972'
  color11: '#95FFC3'
  color12: '#FFFF80'
  color13: '#A0DBFF'
  color14: '#EB71AD'
  color15: '#24E5FF'
  color16: '#FFFFFF'
config:
  gpg: https://raw.githubusercontent.com/drduh/config/master/gpg.conf
fonts:
  main: Montserrat Bold
softwareGroups:
  Basic: &basic
    - bash-completion
    - bat
    - bitwarden-cli
    - chezmoi
    - curl
    - curlie
    - delta
    - direnv
    - docker
    - elasticagent
    - empty-trash
    - exa
    - fd
    - ffsend
    - fkill
    - fzf
    - glances
    - glow
    - gping
    - gtop
    - gum
    - neovim
    - node
    - oh-my-posh
    - skate
    - speed-test
    - task
    - vim
    - wget
    - whalebrew
    - wifi-password
    - zoxide
    - zx
  Basic-Desktop: &basicDesktop
    - *basic
    - brave
    - firefox
    - fonts
    - tabby
    - vscode
  Network-Enabled:
    - cloudflared
    - cockpit
    - cups
    - lexicon
    # - maas
    - ngxtop
  Standard: &standard
    - *basic
    - ansible
    - aria2
    - asdf
    - automake
    - autorestic
    - bandwhich
    - bitly
    - bottom
    - broot
    - cheat
    - commitizen
    - croc
    - ctop
    - dasel
    - dat
    - deno
    - difftastic
    - dog
    - duf
    - dust
    - fq
    - fselect
    - fx
    - gdrive
    - gist
    - git
    - git-lfs
    - git-open
    - glusterfs
    - gnu
    - go
    - gomplate
    - googler
    - gphotos-sync
    - grex
    - gron
    - htop
    - hyperfine
    - imagemagick
    - imgur-uploader
    - is-up
    - jq
    - kvm
    - lxdc
    - m-cli
    - mas
    - mcfly
    - mkcert
    - mycli
    - nb
    - netcat
    - nmap
    - nnn
    - ots
    - pass
    - peco
    - pm2
    - pnpm
    - prettier
    - procs
    - pup
    - pywhat
    - rclone
    - restic
    - ripgrep
    - ripgrep-all
    - rm-improved
    - rsync
    - sd
    - shellcheck
    - serve
    - share
    - sharp
    - spotdl
    - sqlite
    - ssh-vault
    - sysbench
    - t-rec
    - teller
    - tig
    - tinypng
    - tldr
    - tmux
    - translate
    - tree
    - typescript
    - up
    - vagrant
    - vault
    - vim
    - volta
    - watchexec
    - yj
    - ykman
    - youtube-dl
    - yq
    - yubikey-manager
    - zsh
  CLI-Extras:
    - ansibleconnect
  Standard-Desktop: &standardDesktop
    - *basicDesktop
    - autokey
    - balenaetcher
    - bitwarden-cli
    - cerebro
    - chrome
    - clocker
    - cumulus
    - dat-desktop
    - g-assist
    - gimp
    - inkscape
    - jitsi-meet-electron
    - keybase
    - kodi
    - ledgerlive
    - libreoffice
    - lollypop
    - mailspring
    - microsoft-office
    - microsoft-todo
    - motrix
    - nuclear
    # - onionshare
    - parallels
    - peek
    - plex
    - portmaster
    - pretzel
    - proton
    - qtbittorrent
    - qlplugins
    - remote-desktop
    - rofi
    # - secretive
    - sharex
    - shotcut
    - shotwell
    - skype
    - slack
    - stats
    - teams
    - teamviewer
    - temps
    - timeshift
    - virtualbox
    - vlc
    - webtorrent
    - yubikey-authenticator
    - yubikey-manager-qt
    - zoom
  Development: &development
    - *standard
    - act
    - allure
    - angular-cli
    - ansible-lint
    - aqua
    - argocli
    - auto-install
    - automake
    - awscli
    - azurecli
    - azurefunctions
    - bane
    - beets
    - bin
    - browser-sync
    - bundler
    - caniuse
    - carbon-now
    - carthage
    - clair
    - cmake
    - cocoapods
    - composer
    - container-structure-test
    - cookiecutter
    - cordova
    - delve
    - deno
    - desed
    - dframe
    - dive
    - docker-slim
    - dockle
    - dotenv-linter
    - dotnet
    - dprint
    - drone
    - easyengine
    - editly
    - electron
    - emma
    - emoj
    - eslint
    - etcd
    - exiftool
    - fastify
    - feathers
    - filebrowser
    - firebase
    - flutter
    - fpm
    - fq
    - fuego
    - fx
    - gcloud
    - gdown
    - gfi
    - gh
    - ghorg
    - git-filter-repo
    - git-lfs
    - git-secret
    - gitui
    - gitextras
    - gitfuzzy
    - gitlabrunner
    - gitleaks
    - gitomatic
    - gitsome
    - gitstats
    - gixy
    - glab
    - glen
    - go-chromecast
    - go-outline
    - golangci-lint
    - gomodifytags
    - gopkgs
    - gopls
    - gotests
    - grype
    - gulp
    - hadolint
    - hclq
    - heroku
    - hexyl
    - hey
    - hostctl
    - htmlq
    - http-prompt
    - httpie
    - httpstat
    - hub
    - ideviceinstaller
    - impl
    - infracost
    - ionic
    - ios-deploy
    - ipfs
    - ipfs-deploy
    - jiq
    - jo
    - litecli
    - jqp
    - juju
    - libimobiledevice
    - localtunnel
    - mc # TODO
    - mitmproxy
    - mkcert
    - mockoon
    - molecule
    - mycli
    - nativefier
    - ncc
    - nectar
    - nest
    - newman
    - node-prune
    - nomad
    - nomino
    - np
    - npm-check
    - oq
    - package-size
    - packer
    - pageres
    - pandoc
    - pastel
    - pkg
    - playwright
    - psi
    - psu
    - ramda
    - rancher
    - ruby
    - rust
    - s5cmd
    - schema
    - scrcpy
    - sdkman
    - semantic-release
    - sentry-cli
    - serverless
    - shc
    - shdoc
    - shfmt
    - slackterm
    - sloth
    - snitch
    - starred
    - statcode
    - staticcheck
    - stegcloak
    - surge
    - svgo
    - t
    - t-rec
    - terminalizer
    - tokei
    - trellis
    - trivy
    - trufflehog
    - ts2c
    - up
    - upx
    - virtualenv
    - watchexec
    - watchman
    - waypoint
    - websocat
    - whaler
    - winrm-cli
    - wireshark
    - wkhtmltopdf
    - wordpressify
    - wrangler
    - xurls
    - yamllint
    - yank
    - yarn
  Development-Desktop: &developmentDesktop
    - *standardDesktop
    - altair
    - android-studio
    - appium
    - fig
    - filezilla
    - gitdock
    - gitify
    - gitkraken
    - intellij-idea-ce
    - ipfs-desktop
    - iterm2
    - lepton
    - microsoft-edge
    - mjml
    - mqttx
    - postman
    - pre-commit
    - quasar
    - raspberry-pi-imager
    - redis-desktop-manager
    - responsively
    - runjs
    - sqlectron
    - visual-studio
  Experimental: &experimental
    - *development
    - asciicinema
    - assh
    - astronvim
    - awxcli
    - budibase-cli
    - cfssl
    - chef
    - chrome-cli
    - cointop
    - confd
    - consul
    - curator
    - deta
    - difftastic
    - doctl
    - envconsul
    - fission
    - fly
    - fm
    - fselect
    - gdown
    - gojq
    - himalaya
    - lazygit
    - linuxkit
    - logcli
    - mergestat
    - minikube
    - mole
    - muffet
    - nebula
    - osquery
    - page-fetch
    - papertrail
    - poetry
    - pony
    - q
    - sftpgo
    - skm
    - social-analyzer
    - solidity
    - teleport
    - teller
    - termius
    - tfenv
    - tflint
    - tilt
    - vector
  Experimental-Desktop: &experimentalDesktop
    - *developmentDesktop
    - betwixt
    - lens
    - manta
    - mark-text
    - masscode
    - mullvad-vpn
    - powershell
  Kubernetes:
    - kdash
    - kn
    - kubectx
    - kubenav
    - kubernetes-cli
    - kubernetes-helm
    - kubernetes-kompose
    - kubeval
    - linkerd2
    - velero
  deprecated:
    - bivac
    - boilr
    - captain
    - consul-cli
    - consultemplate
    - diffsofancy
    - emplace
    - htop
    - hyper
    - jenv
    - kitty
    - license
    - lpass
    - lsd
    - mackup
    - nvm
    - pyenv
    - raindrop
    - rear
    - sad
    - supdock
    - transfer
    - ulauncher
    - upt
softwarePlugins:
  vim:
    plugins:
      - https://github.com/dense-analysis/ale.git
      - https://github.com/pearofducks/ansible-vim.git
      - https://github.com/neoclide/coc.nvim.git
      - https://github.com/ekalinin/dockerfile.vim.git
      - https://github.com/editorconfig/editorconfig-vim.git
      - https://github.com/junegunn/fzf.git
      - https://github.com/junegunn/fzf.vim.git
      - https://github.com/itchyny/lightline.vim.git
      - https://github.com/scrooloose/nerdtree.git
      - https://github.com/stanangeloff/php.vim.git
      - https://github.com/hdima/python-syntax.git
      - https://github.com/vim-syntastic/syntastic.git
      - https://github.com/vim-airline/vim-airline.git
      - https://github.com/kristijanhusak/vim-carbon-now-sh.git
      - https://github.com/ryanoasis/vim-devicons.git
      - https://github.com/tpope/vim-fugitive.git
      - https://github.com/airblade/vim-gitgutter.git
      - https://github.com/fatih/vim-go.git
      - https://github.com/pangloss/vim-javascript.git
      - https://github.com/mxw/vim-jsx.git
      - https://github.com/plasticboy/vim-markdown.git
      - https://github.com/terryma/vim-multiple-cursors.git
      - https://github.com/prettier/vim-prettier.git
      - https://github.com/tpope/vim-sensible.git
      - https://github.com/tpope/vim-surround.git
      - https://github.com/nanotee/zoxide.vim.git
