---
# The original .chezmoidata.yaml was moved one directory up to software.yml
colors:
  background: '#161925'
  color0: '#161925'
  color1: '#282C34'
  color2: '#ED254E'
  color3: '#71F79F'
  color4: '#F9DC5C'
  color5: '#7CB7FF'
  color6: '#C74D89'
  color7: '#00C1E4'
  color8: '#DCDFE4'
  color9: '#4C5058'
  color10: '#FF4972'
  color11: '#95FFC3'
  color12: '#FFFF80'
  color13: '#A0DBFF'
  color14: '#EB71AD'
  color15: '#24E5FF'
  color16: '#FFFFFF'
config:
  gpg: https://raw.githubusercontent.com/drduh/config/master/gpg.conf
fonts:
  main: Montserrat Bold
softwareGroups:
  terminal:
    - aria2
    - asdf
    - automake
    - autorestic
    - bandwhich
    - bat
    - bitwarden-cli
    - cheat
    - chezmoi
    - cloudflared
    - cmake
    - croc
    - ctop
    - curl
    - curlie
    - dasel
    - delta
    - deno
    - difftastic
    - direnv
    - duf
    - dust
    - etcd
    - exa
    - fd
    - ffsend
    - fq
    - fselect
    - fx
    - fzf
    - gist
    - git
    - git-lfs
    - git-secret
    - gitui
    - glances
    - glow
    - gnu
    - gomplate
    - googler
    - gping
    - grex
    - gron
    - gum
    - hexyl
    - hey
    - htop
    - hyperfine
    - imagemagick
    - jo
    - jq
    - jq
    - litecli
    - m-cli
    - mcfly
    - mkcert
    - mycli
    - nb
    - nmap
    - nnn
    - node
    - ots
    - pass
    - peco
    - pnpm
    - procs
    - pup
    - pywhat
    - rclone
    - restic
    - ripgrep
    - ripgrep-all
    - rm-improved
    - rsync
    - sd
    - shellcheck
    - skate
    - sqlite
    - ssh-vault
    - sysbench
    - task
    - t-rec
    - teller
    - tmux
    - tree
    - up
    - vault
    - vim
    - volta
    - watchexec
    - wget
    - whalebrew
    - yj
    - yq
    - zoxide
    - zsh
    - zx
softwarePlugins:
  vim:
    plugins:
      - https://github.com/dense-analysis/ale.git
      - https://github.com/pearofducks/ansible-vim.git
      - https://github.com/neoclide/coc.nvim.git
      - https://github.com/ekalinin/dockerfile.vim.git
      - https://github.com/editorconfig/editorconfig-vim.git
      - https://github.com/junegunn/fzf.git
      - https://github.com/junegunn/fzf.vim.git
      - https://github.com/itchyny/lightline.vim.git
      - https://github.com/scrooloose/nerdtree.git
      - https://github.com/stanangeloff/php.vim.git
      - https://github.com/hdima/python-syntax.git
      - https://github.com/vim-syntastic/syntastic.git
      - https://github.com/vim-airline/vim-airline.git
      - https://github.com/kristijanhusak/vim-carbon-now-sh.git
      - https://github.com/ryanoasis/vim-devicons.git
      - https://github.com/tpope/vim-fugitive.git
      - https://github.com/airblade/vim-gitgutter.git
      - https://github.com/fatih/vim-go.git
      - https://github.com/pangloss/vim-javascript.git
      - https://github.com/mxw/vim-jsx.git
      - https://github.com/plasticboy/vim-markdown.git
      - https://github.com/terryma/vim-multiple-cursors.git
      - https://github.com/prettier/vim-prettier.git
      - https://github.com/tpope/vim-sensible.git
      - https://github.com/tpope/vim-surround.git
      - https://github.com/nanotee/zoxide.vim.git
