---
colors:
  background: '#161925'
  color0: '#161925'
  color1: '#282C34'
  color2: '#ED254E'
  color3: '#71F79F'
  color4: '#F9DC5C'
  color5: '#7CB7FF'
  color6: '#C74D89'
  color7: '#00C1E4'
  color8: '#DCDFE4'
  color9: '#4C5058'
  color10: '#FF4972'
  color11: '#95FFC3'
  color12: '#FFFF80'
  color13: '#A0DBFF'
  color14: '#EB71AD'
  color15: '#24E5FF'
  color16: '#FFFFFF'
config:
  gpg: https://raw.githubusercontent.com/drduh/config/master/gpg.conf
fonts:
  main: Montserrat Bold
softwareGroups:
  Basic: &basic
    - *CLI
  Basic-Desktop: &basicDesktop
    - *basic
    - brave-browser
    - firefox
    - fonts
    - tabby
    - vlc
    - vscode
  Network-Enabled:
    - cloudflared
    - cockpit
    - cups
    - lexicon
    # - maas
    - ngxtop
  Standard: &standard
    - *basic
    - bitly
    - bottom
    - broot
    - cheat
    - commitizen
    - croc
    - ctop
    - dasel
    - dat
    - deno
    - difftastic
    - dog
    - duf
    - dust
    - fq
    - fselect
    - fx
    - gdrive
    - gist
    - git
    - git-lfs
    - git-open
    - glusterfs
    - gnu
    - go
    - gomplate
    - googler
    - gphotos-sync
    - grex
    - gron
    - htop
    - hyperfine
    - imagemagick
    - imgur-uploader
    - is-up
    - jq
    - kvm
    - lxdc
    - mas
    - mcfly
    - mkcert
    - mycli
    - nb
    - netcat
    - nmap
    - nnn
    - ots
    - pass
    - peco
    - pm2
    - pnpm
    - prettier
    - procs
    - pup
    - pywhat
    - rclone
    - restic
    - ripgrep
    - ripgrep-all
    - rm-improved
    - rsync
    - sd
    - shellcheck
    - serve
    - share
    - sharp
    - spotdl
    - sqlite
    - ssh-vault
    - sysbench
    - t-rec
    - teller
    - tig
    - tinypng
    - tldr
    - tmux
    - translate
    - tree
    - typescript
    - up
    - vagrant
    - vault
    - vim
    - volta
    - watchexec
    - yj
    - ykman
    - youtube-dl
    - yq
    - yubikey-manager
    - zsh
  Standard-Desktop: &standardDesktop
    - *basicDesktop
    - autokey
    - balenaetcher
    - bitwarden-cli
    - cerebro
    - google-chrome
    - clocker
    - cumulus
    - dat-desktop
    - google-assistant
    - gimp
    - inkscape
    - jitsi-meet-electron
    - keybase
    - kodi
    - ledgerlive
    - libreoffice
    - lollypop
    - mailspring
    - microsoft-office
    - microsoft-todo
    - motrix
    - nuclear
    # - onionshare
    - parallels
    - peek
    - plex
    - portmaster
    - pretzel
    - proton
    - qbittorrent
    - qlplugins
    - remote-desktop
    - rofi
    # - secretive
    - sharex
    - shotcut
    - shotwell
    - skype
    - slack
    - stats
    - microsoft-teams
    - teamviewer
    - temps
    - timeshift
    - virtualbox
    - vlc
    - webtorrent
    - yubikey-authenticator
    - yubikey-manager-qt
    - zoom
  Development: &development
    - *standard
    - beets
    - bin
    - browser-sync
    - bundler
    - caniuse
    - carbon-now
    - carthage
    - clair
    - cmake
    - cocoapods
    - composer
    - container-structure-test
    - cookiecutter
    - cordova
    - delve
    - deno
    - desed
    - dframe
    - dive
    - docker-slim
    - dockle
    - dotenv-linter
    - dotnet
    - dprint
    - drone
    - easyengine
    - editly
    - electron
    - emma
    - emoj
    - eslint
    - etcd
    - exiftool
    - fastify
    - feathers
    - filebrowser
    - firebase
    - flutter
    - fpm
    - fq
    - fuego
    - fx
    - gcloud
    - gdown
    - gfi
    - gh
    - ghorg
    - git-filter-repo
    - git-lfs
    - git-secret
    - gitui
    - gitextras
    - gitfuzzy
    - gitlabrunner
    - gitleaks
    - gitomatic
    - gitsome
    - gitstats
    - gixy
    - glab
    - glen
    - go-chromecast
    - go-outline
    - golangci-lint
    - gomodifytags
    - gopkgs
    - gopls
    - gotests
    - grype
    - gulp
    - hadolint
    - hclq
    - heroku
    - hexyl
    - hey
    - hostctl
    - htmlq
    - http-prompt
    - httpie
    - httpstat
    - hub
    - ideviceinstaller
    - impl
    - infracost
    - ionic
    - ios-deploy
    - ipfs
    - ipfs-deploy
    - jiq
    - jo
    - litecli
    - jqp
    - juju
    - libimobiledevice
    - localtunnel
    - mc # TODO
    - mitmproxy
    - mkcert
    - mockoon
    - molecule
    - mycli
    - nativefier
    - ncc
    - nectar
    - nest
    - newman
    - node-prune
    - nomad
    - nomino
    - np
    - npm-check
    - oq
    - package-size
    - packer
    - pageres
    - pandoc
    - pastel
    - pkg
    - playwright
    - psi
    - psu
    - ramda
    - rancher
    - ruby
    - rust
    - s5cmd
    - schema
    - scrcpy
    - sdkman
    - semantic-release
    - sentry-cli
    - serverless
    - shc
    - shdoc
    - shfmt
    - slackterm
    - sloth
    - snitch
    - starred
    - statcode
    - staticcheck
    - stegcloak
    - surge
    - svgo
    - t
    - t-rec
    - terminalizer
    - tokei
    - trellis
    - trivy
    - trufflehog
    - ts2c
    - up
    - upx
    - virtualenv
    - watchexec
    - watchman
    - waypoint
    - websocat
    - whaler
    - winrm-cli
    - wireshark
    - wkhtmltopdf
    - wordpressify
    - wrangler
    - xurls
    - yamllint
    - yank
    - yarn
  Development-Desktop: &developmentDesktop
    - *standardDesktop
    - altair
    - android-studio
    - appium
    - fig
    - filezilla
    - gitdock
    - gitify
    - gitkraken
    - intellij-idea-ce
    - ipfs-desktop
    - iterm2
    - lepton
    - microsoft-edge
    - mjml
    - mqttx
    - postman
    - pre-commit
    - quasar
    - raspberry-pi-imager
    - redis-desktop-manager
    - responsively
    - runjs
    - sqlectron
    - visual-studio
  Experimental: &experimental
    - *development
    - asciicinema
    - assh
    - astronvim
    - awxcli
    - budibase-cli
    - cfssl
    - chef
    - chrome-cli
    - cointop
    - confd
    - consul
    - curator
    - deta
    - difftastic
    - doctl
    - envconsul
    - fission
    - fly
    - fm
    - fselect
    - gdown
    - gojq
    - himalaya
    - lazygit
    - linuxkit
    - logcli
    - mergestat
    - minikube
    - mole
    - muffet
    - nebula
    - osquery
    - page-fetch
    - papertrail
    - poetry
    - pony
    - q
    - sftpgo
    - skm
    - solidity
    - teleport
    - teller
    - termius
    - tfenv
    - tflint
    - tilt
    - vector
  Experimental-Desktop: &experimentalDesktop
    - *developmentDesktop
    - betwixt
    - manta
    - mark-text
    - masscode
    - mullvad-vpn
    - powershell
  Android: &Android
    - scrcpy
  Android-Desktop: &Android-Desktop
    - *Android
    - android-
    - scrcpy-gui
  Ansible: &Ansible
    - ansible
    - ansible-lint
    - ansibleconnect
    - awxcli
    - molecule
    - winrm-cli
  Backup: &Backup
    - autorestic
    - ghorg
    - restic
    - sanoid
  Backup-Desktop: &Backup-Desktop
    - timeshift
  Browsers: &Browsers
    - w3m
  Browsers-Desktop: &Browsers-Desktop
    - brave-browser
    - google-chrome
    - chrome-cli
    - firefox
    - microsoft-edge
  CI: &CI
    - act
    - argo-cli
    - drone-cli
    - fpm
    - gitlab-runner
    - glen
  CLI: &CLI
    - bash-completion
    - bandwhich
    - bat
    - bottom
    - broot
    - cheat
    - chezmoi
    - curl
    - curlie
    - delta
    - direnv
    - dog
    - duf
    - dust
    - empty-trash
    - exa
    - fd
    - fkill
    - fzf
    - glances
    - glow
    - gnu
    - gping
    - gum
    - hyperfine
    - jq
    - mc
    - mcfly
    - nb
    - neovim
    - netcat
    - nmap
    - nnn
    - node
    - oh-my-posh
    - pass
    - procs
    - prettier
    - recoverpy
    - ripgrep
    - ripgrep-all
    - rm-improved
    - rsync
    - sd
    - snapd
    - task
    - tmux
    - tor
    - translate
    - tree
    - vim
    - volta
    - watchexec # file watcher
    - watchman # file watcher
    - wget
    - whalebrew
    - wifi-password
    - yq
    - zoxide
    - zsh
    - zx
  CLI-Extras: &CLI-Extras
    - bin
    - bitly
    - desed
    - emoj
    - fig
    - filebrowser
    - googler
    - grex
    - gron
    - hexyl
    - http-prompt
    - httpie
    - httpstat
    - imgur-uploader
    - is-up
    - jiq
    - jqp
    - litecli
    - mycli
    - nomino
    - normit
    - pastel
    - peco
    - pgcli
    - pywhat
    - slackterm
    - social-analyzer
    - speed-test
    - statcode
    - stegcloak
    - tldr
    - up
    - yank
  Cloud: &Cloud
    - awscli
    - azure-cli
    - azurefunctions
    - budibase-cli
    - consul-cli
    - curator
    - doctl
    - envconsul
    - fission
    - fly
    - gcloud
    - heroku
    - juju
    - lexicon
    - logcli
    - psu
    - rancher-cli
  Cloud-Storage: &Cloud-Storage
    - gdrive
    - gphotos-sync
    - rclone
    - s5cmd
  Crypto: &Crypto
    - cointop
  Crypto-Desktop: &Crypto-Desktop
    - *Crypto
    - keybase
    - ledger-live
    - monero
    # - onionshare
    - onlykey
  Data-Manipulation: &Data-Manipulation
    - dasel
    - fq
    - fselect
    - fx
    - gojq
    - hclq
    - htmlq
    - jo
    - jq
    - oq
    - osquery
    - pup
    - q
    - ramda
    - schema
    - transfer
    - xurls
    - yj
    - yq
  E-mail: &E-mail
    - himalaya
  E-mail-Desktop: &E-mail-Desktop
    - mailspring
    - protonmail-bridge
  Database: &Database
    - sqlite
  Database-Desktop: &Database-Desktop
    - sqlectron
  Misc-Desktop: &Desktop
    - cerebro
    - clocker
    - cumulus
    - pretzel
    - qlplugins
    - remote-desktop
    - rofi
    - secretive
    - stats
    - temps
    - teamviewer
  Essentials-Desktop: &Desktop-Essential
    - tabby
    - vscode
  Ansible-Roles:
    - ssh
    - swarm
    - vpn
    - wsl
    - yubikey
    - antivirus
    - common
    - connect
    - debloat
    - defaultbrowser
    - desktop
    - disks
    - dns
    - dnsmasq
    - easyengine
    - environment
    - extensions
    - finish
    - firewall
    - fuse
    - guacamole
    - hosthomepage
    - hosts
    - motd
    - pfsense
    - pihole
    - pip
    - prepare
    - security
    - ssh
    - swarm
    - maas
  Social-Networking: &Social-Networking
    - social-analyzer
    - t
  Misc-Development-Tools: &Misc-Development-Tools
    - aqua
    # - asdf # Handled by dotfiles
    # - astronvim
    - automake
    - bundler
    - carthage
    - chef
    - cmake
    - cocoapods
    - dotnet
    - gradle
    - ideviceinstaller
    - ios-deploy
    - java
    - libimobiledevice
    - php
    - ruby
    - rust
    - sdkman
    - solidity
    - upx
    - windows-adk
    - windows-admin-center
    - windows-power-toys
  Shell-Scripting: &Shell-Scripting
    - shc
    - shdoc
    - shellcheck
    - shfmt
  Development-Tools-Desktop: &Development-Tools-Desktop
    - intellij-idea-ce
    - iterm2
    - lepton # snippet manager
    - masscode # snippet manager
    - powershell
    - redis-desktop-manager
    - visual-studio
    - xcode
  DNS: &DNS
    - hostctl
    - switchhosts
  Docker: &Docker
    - bane
    - clair
    - container-structure-test
    - dive
    - docker
    - docker-slim
    - dockerpushrm
    - dockle
    - grype
    - gvisor
    - supdock
    - trivy
    - trufflehog
    - whaler
  Finance: &Finance
    - infracost
  Finance-Desktop: &Finance-Desktop
    - manta
  Git: &Git
    - commitizen
    - gh
    - gist
    - git
    - git-extras
    - git-filter-repo
    - git-fuzzy
    - git-lfs
    - git-open
    - git-secret
    - gitomatic
    - gitsome
    - git-stats
    - gitui
    - glab
    - hub
    - lazygit
    - mergestat
    - starred
    - tig
  Communication-Desktop: &Communication-Desktop
    - microsoft-teams
    - jitsi-meet
    - skype
    - slack
    - zoom
  Git-Desktop: &Git-Desktop
    - *Git
    - gitdock
    - gitify
    - gitkraken
  Go: &Go
    - delve
    - go
    - go-outline
    - gomodifytags
    - gopkgs
    - gopls
    - gotests
    - impl
    - staticcheck
    - wails
  Home: &Home
    - go-chromecast
  Linting: &Linting
    - ansible-lint
    - dotenv-linter
    - dprint
    - eslint
    - gitleaks
    - golangci-lint
    - hadolint
    - pre-commit
    - shellcheck
    - shfmt
    - tflint
    - tokei
    - yamllint
  Logging: &Logging
    - fuego
    - papertrail
    - sentry-cli
  NGINX: &NGINX
    - certbot
    - cfssl
    - gixy
    - mkcert
    - nginx
    - ngxtop
  Package-Management: &Package-Management
    - homebrew
    - whalebrew
    - zap
  Testing: &Testing
    - allure
    - appium
    - molecule
  Testing-Desktop: &Testing-Desktop
    - *Testing
  Kubernetes: &Kubernetes
    - cmctl
    - kdash
    - kn
    - kubectx
    - kubenav
    - kubernetes-cli
    - kubernetes-helm
    - kubernetes-kompose
    - kubeval
    - linkerd2
    - minikube
    - tilt
    - velero
  Kubernetes-Desktop: &Kubernetes-Desktop
    - *Kubernetes
    - lens
  Media: &Media
    - beets
    - editly
    - exiftool
    - ffmpeg
    - imagemagick
    - pandoc
    - sharp
    - spotdl
    - svgo
    - tinypng
    - wkhtmltopdf
    - youtube-dl
  Media-Desktop: &Media-Desktop
    - balenaetcher
    - gimp
    - inkscape
    - kodi
    - lollypop
    - nuclear
    - plex
    - raspberry-pi-imager
    - shotcut
    - shotwell
    - vlc
  Networking: &Networking
    - etcd
    - cloudflared
    - glusterfs
    - mole
    - nebula
    - ngrok
    - ssl-proxy
    - tailscale
    - warp
  PHP: &PHP
    - composer
    - php
  Productivity-Desktop: &Productivity-Desktop
    - libreoffice
    - microsoft-office
    - microsoft-todo
  Python: &Python
    - poetry
    - python
    - virtualenv
  Recording: &Recording
    - asciinema
    - carbon-now
    - dframe
    - t-rec
  Ruby: &Ruby
    - ruby
  Recording-Desktop: &Recording-Desktop
    - peek
    - sharex
  Security: &Security
    - bitwarden-cli
    - pony
    - skate
    - ssh-vault
    - teller
    - vault
    - ykman
    - yubikey-manager
  Security-Desktop: &Security-Desktop
    - *Security
    - bitwarden
    - mullvad-vpn
    - nordvpn
    - portmaster
    - protonvpn
    - santa
    - yubikey-authenticator
    - yubikey-manager-qt
  Server: &Server
    - cockpit
    - consul
    - cups
    - elastic-agent
    - netdata
    - samba
    - sftpgo
    - vector
    - wazuh
  SSH: &SSH
    - assh
    - skm
    - ssh-vault
    - sshpass
    - ssh-tarpit
    - sync-ssh-keys
    - teleport
  Sys-Admin: &Sys-Admin
    - ctop
    - gtop
    - htop
    - sysbench
    - sysdig
    - sysget # universal package-management
    - upt # universal package-management
    - winrm-cli
    - wireshark-cli
  Sys-Admin-Desktop: &Sys-Admin-Desktop
    - quasar
    - sloth
    - snitch
    - wireshark
  Templates: &Templates
    - confd
    - cookiecutter
    - gomplate
  Transfer: &Transfer
    - aria2
    - croc
    - dat
    - ffsend
    - gdown
    - ots
    - share
  Misc-Tools: &Misc-Tools
    - nomad
    - pm2
    - waypoint
  Transfer-Desktop: &Transfer-Desktop
    - dat-desktop
    - filezilla
    - motrix
    - qbittorrent
    - webtorrent
  Terraform: &Terraform
    - terraform
    - tfenv
    - tflint
  Utilities: &Utilities
    - nativefier
  Virtualization: &Virtualization
    - kvm
    - linuxkit
    - lxdc
    - multipass
    - packer
    - vagrant
  Virtualization-Desktop: &Virtualization-Desktop
    - *Virtualization
    - parallels
    - virtualbox
    - vmware
  Web-Development: &Web-Development
    - angular-cli
    - auto-install
    - browser-sync
    - caniuse
    - cordova
    - deno
    - electron
    - emma
    - fastify
    - feathers
    - firebase
    - flutter
    - gfi
    - gulp
    - hey
    - ionic
    - ipfs
    - ipfs-deploy
    - localtunnel
    - mitmproxy
    - muffet
    - ncc
    - nectar
    - nest
    - newman
    - ngrok
    - node-prune
    - np
    - npm-check
    - oclif
    - package-size
    - page-fetch
    - pageres
    - pkg
    - playwright
    - pnpm
    - psi
    - semantic-release
    - serve
    - serverless
    - surge
    - trellis
    - ts2c
    - websocat
    - wordpressify
    - wp-cli
    - wrangler
    - wrk
    - yarn
  Web-Development-Desktop: &Web-Development-Desktop
    - *Web-Development
    - altair
    - betwixt
    - ipfs-desktop
    - mjml
    - mockoon
    - mqttx
    - postman
    - responsively
    - runjs
  deprecated:
    - apt-cacher-ng
    - bivac
    - boilr
    - captain
    - consul-template
    - diffsofancy
    - difftastic
    - emplace
    - gvm
    - htop
    - hyper
    - jenv
    - kitty
    - license
    - lpass
    - lsd
    - mackup
    - nvm
    - pyenv
    - s3filesystem
    - starship
    - raindrop
    - rear
    - rvm
    - sad
    - supdock
    - termius
    - transfer
    - ulauncher
    - upt
softwarePlugins:
  vim:
    plugins:
      - https://github.com/dense-analysis/ale.git
      - https://github.com/pearofducks/ansible-vim.git
      - https://github.com/neoclide/coc.nvim.git
      - https://github.com/ekalinin/dockerfile.vim.git
      - https://github.com/editorconfig/editorconfig-vim.git
      - https://github.com/junegunn/fzf.git
      - https://github.com/junegunn/fzf.vim.git
      - https://github.com/itchyny/lightline.vim.git
      - https://github.com/scrooloose/nerdtree.git
      - https://github.com/stanangeloff/php.vim.git
      - https://github.com/hdima/python-syntax.git
      - https://github.com/vim-syntastic/syntastic.git
      - https://github.com/vim-airline/vim-airline.git
      - https://github.com/kristijanhusak/vim-carbon-now-sh.git
      - https://github.com/ryanoasis/vim-devicons.git
      - https://github.com/tpope/vim-fugitive.git
      - https://github.com/airblade/vim-gitgutter.git
      - https://github.com/fatih/vim-go.git
      - https://github.com/pangloss/vim-javascript.git
      - https://github.com/mxw/vim-jsx.git
      - https://github.com/plasticboy/vim-markdown.git
      - https://github.com/terryma/vim-multiple-cursors.git
      - https://github.com/prettier/vim-prettier.git
      - https://github.com/tpope/vim-sensible.git
      - https://github.com/tpope/vim-surround.git
      - https://github.com/nanotee/zoxide.vim.git
