---
colors:
  background: '#161925'
  color0: '#161925'
  color1: '#282C34'
  color2: '#ED254E'
  color3: '#71F79F'
  color4: '#F9DC5C'
  color5: '#7CB7FF'
  color6: '#C74D89'
  color7: '#00C1E4'
  color8: '#DCDFE4'
  color9: '#4C5058'
  color10: '#FF4972'
  color11: '#95FFC3'
  color12: '#FFFF80'
  color13: '#A0DBFF'
  color14: '#EB71AD'
  color15: '#24E5FF'
  color16: '#FFFFFF'
config:
  gpg: https://raw.githubusercontent.com/drduh/config/master/gpg.conf
fonts:
  main: Montserrat Bold
softwareGroups:
  Android: &Android
    - scrcpy
  Android-Desktop: &Android-Desktop
    - android-studio
    - scrcpy-gui
  Ansible: &Ansible
    - ansible
    - ansible-lint
    - ansibleconnect
    - awxcli
    - molecule
    - winrm-cli
  Ansible-Roles: &Ansible-Roles
    - ssh
    - swarm
    - vpn
    - wsl
    - yubikey
    - antivirus
    - common
    - connect
    - debloat
    - defaultbrowser
    - desktop
    - disks
    - dns
    - dnsmasq
    - easyengine
    - environment
    - extensions
    - finish
    - firewall
    - fuse
    - guacamole
    - hosthomepage
    - hosts
    - motd
    - pfsense
    - pihole
    - pip
    - prepare
    - security
    - ssh
    - swarm
    - maas
  Backup: &Backup
    - autorestic
    - ghorg
    - restic
    - sanoid
  Backup-Desktop: &Backup-Desktop
    - timeshift
  Browsers: &Browsers
    - w3m
  Browsers-Desktop: &Browsers-Desktop
    - brave-browser
    - google-chrome
    - chrome-cli
    - firefox
    - microsoft-edge
  CI: &CI
    - act
    - argo-cli
    - drone-cli
    - fpm
    - gitlab-runner
    - glen
  CLI: &CLI
    - bash-completion
    - bandwhich
    - bat
    - bottom
    - broot
    - cheat
    - chezmoi
    - curl
    - curlie
    - delta
    - direnv
    - dog
    - duf
    - dust
    - empty-trash
    - exa
    - fd
    - fkill
    - fzf
    - git
    - glances
    - glow
    - gnu
    - gping
    - gum
    - hyperfine
    - jq
    - mc
    - mcfly
    - nb
    - neovim
    - netcat
    - nmap
    - nnn
    - node
    - oh-my-posh
    - pass
    - procs
    - prettier
    - recoverpy
    - ripgrep
    - ripgrep-all
    - rm-improved
    - rsync
    - sd
    - snapd
    - task
    - tmux
    - tor
    - translate
    - tree
    - vim
    - volta
    - watchexec
    - watchman
    - wget
    - whalebrew
    - wifi-password
    - yq
    - zoxide
    - zsh
    - zx
  CLI-Extras: &CLI-Extras
    - bin
    - bitly
    - desed
    - emoj
    - fig
    - filebrowser
    - googler
    - grex
    - gron
    - hexyl
    - http-prompt
    - httpie
    - httpstat
    - imgur-uploader
    - is-up
    - jiq
    - jqp
    - litecli
    - mycli
    - nomino
    - normit
    - pastel
    - peco
    - pgcli
    - pywhat
    - slackterm
    - social-analyzer
    - speed-test
    - statcode
    - stegcloak
    - tldr
    - up
    - yank
  Cloud: &Cloud
    - awscli
    - azure-cli
    - azurefunctions
    - budibase-cli
    - consul-cli
    - curator
    - doctl
    - envconsul
    - fission
    - fly
    - gcloud
    - heroku
    - juju
    - lexicon
    - logcli
    - psu
    - rancher-cli
  Cloud-Storage: &Cloud-Storage
    - gdrive
    - gphotos-sync
    - rclone
    - s5cmd
  Communication-Desktop: &Communication-Desktop
    - microsoft-teams
    - jitsi-meet
    - skype
    - slack
    - zoom
  Crypto: &Crypto
    - cointop
  Crypto-Desktop: &Crypto-Desktop
    - keybase
    - ledger-live
    - monero
    # - onionshare
    - onlykey
  DNS: &DNS
    - hostctl
    - switchhosts
  Data-Manipulation: &Data-Manipulation
    - dasel
    - fq
    - fselect
    - fx
    - gojq
    - hclq
    - htmlq
    - jo
    - jq
    - oq
    - osquery
    - pup
    - q
    - ramda
    - schema
    - transfer
    - xurls
    - yj
    - yq
  Database: &Database
    - sqlite
  Database-Desktop: &Database-Desktop
    - sqlectron
  Development-Tools-Desktop: &Development-Tools-Desktop
    - intellij-idea-ce
    - iterm2
    - lepton
    - masscode
    - powershell
    - redis-desktop-manager
    - visual-studio
    - xcode
  Docker: &Docker
    - bane
    - clair
    - container-structure-test
    - dive
    - docker
    - docker-slim
    - dockerpushrm
    - dockle
    - grype
    - gvisor
    - supdock
    - trivy
    - trufflehog
    - whaler
  E-mail: &E-mail
    - himalaya
  E-mail-Desktop: &E-mail-Desktop
    - mailspring
    - protonmail-bridge
  Essentials: &Essentials
    - docker
  Essentials-Desktop: &Essentials-Desktop
    - firefox
    - portainer
    - tabby
    - vlc
    - vscode
  Finance: &Finance
    - infracost
  Finance-Desktop: &Finance-Desktop
    - manta
  Git: &Git
    - commitizen
    - gh
    - gist
    - git
    - git-extras
    - git-filter-repo
    - git-fuzzy
    - git-lfs
    - git-open
    - git-secret
    - gitomatic
    - gitsome
    - git-stats
    - gitui
    - glab
    - hub
    - lazygit
    - mergestat
    - starred
    - tig
  Git-Desktop: &Git-Desktop
    - *ref_4
    - gitdock
    - gitify
    - gitkraken
  Go: &Go
    - delve
    - go
    - go-outline
    - gomodifytags
    - gopkgs
    - gopls
    - gotests
    - impl
    - staticcheck
    - wails
  Home: &Home
    - go-chromecast
  Kubernetes: &Kubernetes
    - cmctl
    - kdash
    - kn
    - kubectx
    - kubenav
    - kubernetes-cli
    - kubernetes-helm
    - kubernetes-kompose
    - kubeval
    - linkerd2
    - minikube
    - tilt
    - velero
  Kubernetes-Desktop: &Kubernetes-Desktop
    - lens
  Linting: &Linting
    - ansible-lint
    - dotenv-linter
    - dprint
    - eslint
    - gitleaks
    - golangci-lint
    - hadolint
    - pre-commit
    - shellcheck
    - shfmt
    - tflint
    - tokei
    - yamllint
  Logging: &Logging
    - fuego
    - papertrail
    - sentry-cli
  Media: &Media
    - beets
    - editly
    - exiftool
    - ffmpeg
    - imagemagick
    - pandoc
    - sharp
    - spotdl
    - svgo
    - tinypng
    - wkhtmltopdf
    - youtube-dl
  Media-Desktop: &Media-Desktop
    - balenaetcher
    - gimp
    - inkscape
    - kodi
    - lollypop
    - nuclear
    - plex
    - raspberry-pi-imager
    - shotcut
    - shotwell
    - vlc
  Misc-Desktop: &Misc-Desktop
    - cerebro
    - clocker
    - cumulus
    - pretzel
    - qlplugins
    - remote-desktop
    - rofi
    - secretive
    - stats
    - temps
    - teamviewer
  Misc-Development-Tools: &Misc-Development-Tools
    - aqua
    # - asdf # Handled by dotfiles
    # - astronvim
    - automake
    - bundler
    - carthage
    - chef
    - cmake
    - cocoapods
    - dotnet
    - gradle
    - ideviceinstaller
    - ios-deploy
    - java
    - libimobiledevice
    - rust
    - sdkman
    - solidity
    - upx
    - windows-adk
    - windows-admin-center
    - windows-power-toys
  NGINX: &NGINX
    - certbot
    - cfssl
    - gixy
    - mkcert
    - nginx
    # - maas
    - ngxtop
  Network-Enabled: &Network-Enabled
    - cockpit
    - cups
    - lexicon
  Networking: &Networking
    - etcd
    - cloudflared
    - glusterfs
    - mole
    - nebula
    - ngrok
    - ssl-proxy
    - tailscale
    - warp
  Orchestration: &Orchestration
    - nomad
    - pm2
    - waypoint
  PHP: &PHP
    - composer
    - php
  Package-Management: &Package-Management
    - homebrew
    - whalebrew
    - zap
  Productivity-Desktop: &Productivity-Desktop
    - libreoffice
    - microsoft-office
    - microsoft-todo
  Python: &Python
    - poetry
    - python
    - virtualenv
  Recording: &Recording
    - asciinema
    - carbon-now
    - dframe
    - t-rec
  Recording-Desktop: &Recording-Desktop
    - peek
    - sharex
  Ruby: &Ruby
    - ruby
  SSH: &SSH
    - assh
    - skm
    - ssh-vault
    - sshpass
    - ssh-tarpit
    - sync-ssh-keys
    - teleport
  Security: &Security
    - bitwarden-cli
    - pony
    - skate
    - ssh-vault
    - teller
    - vault
    - ykman
    - yubikey-manager
  Security-Desktop: &Security-Desktop
    - bitwarden
    - mullvad-vpn
    - portmaster
    - protonvpn
    - santa
    - yubikey-authenticator
    - yubikey-manager-qt
  Server: &Server
    - cockpit
    - consul
    - cups
    - elastic-agent
    - netdata
    - samba
    - sftpgo
    - vector
    - wazuh
  Shell-Scripting: &Shell-Scripting
    - shc
    - shdoc
    - shellcheck
    - shfmt
  Social-Networking: &Social-Networking
    - social-analyzer
    - t
  Sys-Admin: &Sys-Admin
    - ctop
    - gtop
    - htop
    - sysbench
    - sysdig
    - sysget
    - upt
    - winrm-cli
    - wireshark-cli
  Sys-Admin-Desktop: &Sys-Admin-Desktop
    - quasar
    - sloth
    - snitch
    - wireshark
  Templates: &Templates
    - confd
    - cookiecutter
    - gomplate
  Terraform: &Terraform
    - terraform
    - tfenv
    - tflint
  Testing: &Testing
    - allure
    - appium
    - molecule
  Transfer: &Transfer
    - aria2
    - croc
    - dat
    - ffsend
    - gdown
    - ots
    - share
  Transfer-Desktop: &Transfer-Desktop
    - dat-desktop
    - filezilla
    - motrix
    - qbittorrent
    - webtorrent
  Utilities: &Utilities
    - nativefier
  Virtualization: &Virtualization
    - kvm
    - linuxkit
    - lxdc
    - multipass
    - packer
    - vagrant
  Virtualization-Desktop: &Virtualization-Desktop
    - parallels
    - virtualbox
    - vmware
  Web-Development: &Web-Development
    - angular-cli
    - auto-install
    - browser-sync
    - caniuse
    - cordova
    - deno
    - electron
    - emma
    - fastify
    - feathers
    - firebase
    - flutter
    - gfi
    - gulp
    - hey
    - ionic
    - ipfs
    - ipfs-deploy
    - localtunnel
    - mitmproxy
    - muffet
    - ncc
    - nectar
    - nest
    - newman
    - ngrok
    - node-prune
    - np
    - npm-check
    - oclif
    - package-size
    - page-fetch
    - pageres
    - pkg
    - playwright
    - pnpm
    - psi
    - semantic-release
    - serve
    - serverless
    - surge
    - trellis
    - ts2c
    - websocat
    - wordpressify
    - wp-cli
    - wrangler
    - wrk
    - yarn
  Web-Development-Desktop: &Web-Development-Desktop
    - altair
    - betwixt
    - ipfs-desktop
    - mjml
    - mockoon
    - mqttx
    - postman
    - responsively
    - runjs
  _Basic: &_Basic
    << : [*CLI, *Essentials]
  _Basic-Desktop: &_Basic-Desktop
    << : [*_Basic, *Essentials-Desktop]
  _Standard: &_Standard
    << : [*_Basic, *Backup, *Cloud-Storage]
    - bitwarden-cli
  _Standard-Desktop: &_Standard-Desktop
    << : [*_Basic-Desktop, *Backup-Desktop, *Communication-Desktop, *Media-Desktop, *Misc-Desktop, *Productivity-Desktop, *Recording-Desktop, *Virtualization-Desktop]
    - bitwarden
    - brave-browser
    - mailspring
    - protonvpn
    - tailscale
    - warp
  _Full: &_Development
    << : [*_Standard, *Android, *Ansible, *Backup, *Browsers, *CI, *CLI-Extras, *Cloud, *Cloud-Storage, *Crypto, *DNS, *Data-Manipulation, *Database, *Docker, *E-mail, *Finance, *Git, *Go, *Home, *Kubernetes, *Linting, *Logging, *Media, *Misc-Development-Tools, *NGINX, *Network-Enabled, *Networking, *Orchestration, *PHP, *Package-Management, *Python, *Recording, *Ruby, *SSH, *Security, *Server, *Shell-Scripting, *Social-Networking, *Sys-Admin, *Terraform, *Templates, *Testing, *Transfer, *Utilities, *Virtualization, *Web-Development]
  _Full-Desktop: &_Development-Desktop
    << : [*_Full, *_Standard-Desktop, *Android-Desktop, *Backup-Desktop, *Browsers-Desktop, *Communication-Desktop, *Crypto-Desktop, *Database-Desktop, *Development-Tools-Desktop, *E-mail-Desktop, *Finance-Desktop, *Git-Desktop, *Kubernetes-Desktop, *Media-Desktop, *Misc-Desktop, *Productivity-Desktop, *Recording-Desktop, *Security-Desktop, *Sys-Admin-Desktop, *Transfer-Desktop, *Virtualization-Desktop, *Web-Development-Desktop]
  deprecated:
    - apt-cacher-ng
    - bivac
    - boilr
    - captain
    - consul-template
    - diffsofancy
    - difftastic
    - emplace
    - gvm
    - htop
    - hyper
    - jenv
    - kitty
    - license
    - lpass
    - lsd
    - mackup
    - nordvpn
    - nvm
    - pyenv
    - s3filesystem
    - starship
    - raindrop
    - rear
    - rvm
    - sad
    - supdock
    - termius
    - transfer
    - ulauncher
softwarePlugins:
  vim:
    plugins:
      - https://github.com/dense-analysis/ale.git
      - https://github.com/pearofducks/ansible-vim.git
      - https://github.com/neoclide/coc.nvim.git
      - https://github.com/ekalinin/dockerfile.vim.git
      - https://github.com/editorconfig/editorconfig-vim.git
      - https://github.com/junegunn/fzf.git
      - https://github.com/junegunn/fzf.vim.git
      - https://github.com/itchyny/lightline.vim.git
      - https://github.com/scrooloose/nerdtree.git
      - https://github.com/stanangeloff/php.vim.git
      - https://github.com/hdima/python-syntax.git
      - https://github.com/vim-syntastic/syntastic.git
      - https://github.com/vim-airline/vim-airline.git
      - https://github.com/kristijanhusak/vim-carbon-now-sh.git
      - https://github.com/ryanoasis/vim-devicons.git
      - https://github.com/tpope/vim-fugitive.git
      - https://github.com/airblade/vim-gitgutter.git
      - https://github.com/fatih/vim-go.git
      - https://github.com/pangloss/vim-javascript.git
      - https://github.com/mxw/vim-jsx.git
      - https://github.com/plasticboy/vim-markdown.git
      - https://github.com/terryma/vim-multiple-cursors.git
      - https://github.com/prettier/vim-prettier.git
      - https://github.com/tpope/vim-sensible.git
      - https://github.com/tpope/vim-surround.git
      - https://github.com/nanotee/zoxide.vim.git