{{- if not .host.headless }}
## Betelgeuse Theme
["/usr/local/src/betelgeuse"]
    type = "git-repo"
    url = "https://gitlab.com/megabyte-labs/misc/betelgeuse.git"
    clone.args = ["--depth", "1"]
    pull.args = ["--ff-only"]

### Hack Nerd Font Download
{{-   $refreshPeriod := "4800h" }}
{{-   $fontDir := "" }}
{{-   $fontUrlBase := "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack"}}
{{-   if eq .host.distro.family "darwin" }}
{{-     $fontDir = "/Library/Fonts" }}
{{-   else if eq .host.distro.family "linux" }}
{{-     $fontDir = "/usr/local/share/fonts" }}
{{-   else if eq .host.distro.family "windows" }}
{{-     $fontDir = "TODOWindows/Fonts" }}
{{-   end }}
["{{ $fontDir }}/Hack-Regular-Nerd-Font.ttf"]
    type = "file"
    url = "{{ $fontUrlBase }}/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete{{if eq .host.distro.family "windows"}}%20Windows%20Compatible{{end}}.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
["{{ $fontDir }}/Hack-Bold-Nerd-Font.ttf"]
    type = "file"
    url = "{{ $fontUrlBase }}/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete{{if eq .host.distro.family "windows"}}%20Windows%20Compatible{{end}}.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
["{{ $fontDir }}/Hack-Italic-Nerd-Font.ttf"]
    type = "file"
    url = "{{ $fontUrlBase }}/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete{{if eq .host.distro.family "windows"}}%20Windows%20Compatible{{end}}.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
["{{ $fontDir }}/Hack-Bold-Italic-Nerd-Font.ttf"]
    type = "file"
    url = "{{ $fontUrlBase }}/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete{{if eq .host.distro.family "windows"}}%20Windows%20Compatible{{end}}.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"

### Montserrat Font Download
{{-   $fontUrlBase := "https://github.com/JulietaUla/Montserrat/raw/master/fonts/ttf/Montserrat-"}}
{{-   $fonts := list "Black" "BlackItalic" "Bold" "BoldItalic" "ExtraBold" "ExtraBoldItalic" "ExtraLight" "ExtraLightItalic" "Italic" "Light" "LightItalic" "Medium" "MediumItalic" "Regular" "SemiBold" "SemiBoldItalic" "Thin" "ThinItalic" }}
{{-   range $font := $fonts }}
["{{ $fontDir }}/Montserrat-{{ $font }}.ttf"]
    type = "file"
    url = "{{ $fontUrlBase }}{{ $font }}.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
{{-   end }}

### ZillaSlab Font Download
{{-   $fontUrlBase := "https://github.com/typotheque/zilla-slab/raw/master/fonts_TTF/ZillaSlab"}}
{{-   $fonts := list "-Bold" "-BoldItalic" "-Italic" "-Light" "-LightItalic" "-Medium" "-MediumItalic" "-Regular" "-SemiBold" "-SemiBoldItalic" "Highlight-Bold" "Highlight-Regular" }}
{{-   range $font := $fonts }}
["{{ $fontDir }}/ZillaSlab{{ $font }}.ttf"]
    type = "file"
    url = "{{ $fontUrlBase }}{{ $font }}.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
{{-   end }}

### Rofi Fonts
["{{ $fontDir }}/GrapeNuts-Regular.ttf"]
    type = "file"
    url = "https://github.com/adi1090x/rofi/raw/master/fonts/GrapeNuts-Regular.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
["{{ $fontDir }}/Icomoon-Feather.ttf"]
    type = "file"
    url = "https://github.com/adi1090x/rofi/raw/master/fonts/Icomoon-Feather.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
["{{ $fontDir }}/Iosevka-Nerd-Font-Complete.ttf"]
    type = "file"
    url = "https://github.com/adi1090x/rofi/raw/master/fonts/Iosevka-Nerd-Font-Complete.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
["{{ $fontDir }}/JetBrains-Mono-Nerd-Font-Complete.ttf"]
    type = "file"
    url = "https://github.com/adi1090x/rofi/raw/master/fonts/JetBrains-Mono-Nerd-Font-Complete.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"

### Miscellaneous Fonts Download
["{{ $fontDir }}/FontAwesome.ttf"]
    type = "file"
    # Source URL
    url = "https://github.com/VermiumSifell/dotfiles/raw/main/dot_local/share/fonts/fontawesome.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
["{{ $fontDir }}/Weather-Icons.ttf"]
    type = "file"
    # Source URL
    url = "https://github.com/VermiumSifell/dotfiles/raw/main/dot_local/share/fonts/weathericons.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
{{- end }}

### NGINX
["/etc/nginx"]
    type = "git-repo"
    url = "https://gitlab.com/megabyte-labs/cloud/nginx-configs.git"
    clone.args = ["--depth", "1"]
    pull.args = ["--ff-only"]

### Rundeck
["/var/lib/rundeck/libext/ansible-plugin-3.2.2.jar"]
    type = "file"
    url = "https://github.com/rundeck-plugins/ansible-plugin/releases/download/v3.2.2/ansible-plugin-3.2.2.jar"
    refreshPeriod = "{{ $refreshPeriod }}"
