---
# `softwarePackages` is a map of possible package managers to use while installing a program. The installer will
# look at the `installerPreference` variable (bottom of file) and find the first package manager that is in the package's possible
# installation method and then use that. It is also sensitive to the type of operating system so a package with
# only `apt` defined will not install on macOS.
#
# Everything should be fairly straight forward. Take a look at the `installerPreference` for a list of package managers. If a package
# has dependencies, the dependencies are defined under the `_deps` key. All of the `_deps` should also be defined in the
# `softwarePackages` map. The installer will check for the presence of the package's key in the PATH. If the package's key
# does not match the executable's name, then the `_bin` key can be defined so that the installer will look at that instead.
softwarePackages:
  altair:
    cask: altair-graphql-client
    choco: altair-graphql
    snap: altair
    yay: altair
  angular-cli:
    brew: angular-cli
    npm: '@angular/cli'
  ansible-lint:
    pipx: ansible-lint
  ansible:
    brew: ansible
    dnf: ansible
    pipx: ansible
  ansibleconnect:
    _deps:
      - sshpass
      - tmux
    pipx: ansibleconnect
  asciicinema:
    pipx: asciicinema
  astronvim:
    _deps:
      - bottom
      # Conflicts with coreutils binary on macOS
      # - gdu
      - lazygit
      - neovim
      - node
      - python
      - ripgrep
      - tree-sitter
  auto-install:
    npm: auto-install
  automake:
    brew: automake
  bat:
    apk: bat
    apt: bat
    brew: bat
    cargo: bat
    choco: bat
    pacman: bat
    pkg: bat
    port: bat
    scoop: bat
    zypper: bat
  delta:
    brew: git-delta
    scoop: delta
  bash-completion:
    brew: bash-completion
  bitly:
    npm: bitly-cli-client
  bottom:
    brew: bottom
    pacman: bottom
    scoop: bottom
    snap: bottom
  browser-sync:
    npm: browser-sync
  bw:
    choco: bitwarden-cli
    snap: bw
  caniuse:
    npm: caniuse-cmd
  carbon-now:
    npm: carbon-now-cli
  carthage:
    brew:darwin: carthage
  chrome-cli:
    brew:darwin: chrome-cli
  clocker:
    cask: clocker
  cookiecutter:
    brew: cookiecutter
    pipx: cookiecutter
  commitizen:
    _bin: cz
    npm: commitizen
  cordova:
    npm: cordova
  dframe:
    npm: deviceframe
  editly:
    npm: editly
  electron:
    brew: electron
    npm: electron
  emma:
    npm: emma-cli
  emoj:
    npm: emoj
  emplace:
    cargo: emplace
    nix: emplace
    scoop: emplace
  empty-trash:
    npm: empty-trash-cli
  eslint:
    brew: eslint
    npm: eslint
  fastify:
    npm: fastify-cli
  feathers:
    npm: '@feathersjs/cli'
  firebase:
    npm: firebase-tools
  ffmpeg:
    apk: ffmpeg
    apt: ffmpeg
    brew: ffmpeg
    choco: ffmpeg
    dnf: ffmpeg
    pacman: ffmpeg
    scoop: ffmpeg
  fkill:
    npm: fkill-cli
  fonts:
    cask:
      - epk/epk/font-sf-mono-nerd-font
      - homebrew/cask-fonts/font-hack-nerd-font
      - homebrew/cask-fonts/font-meslo-lg-nerd-font
  gdown:
    pipx: gdown
  gdu:
    brew: gdu
    go: github.com/dundee/gdu/v5/cmd/gdu@latest
    pacman: gdu
    snap: gdu-disk-usage-analyzer
  gdu:debian:
    apt: gdu
  gfi:
    npm: google-font-installer
  git:
    apk: git
    apt: git
    brew: git
    dnf: git
  git-filter-repo:
    brew: git-filter-repo
    pipx: git-filter-repo
  git-lfs:
    _deps:
      - git
    brew: git-lfs
    scoop: git-lfs
  git-open:
    npm: git-open
  gixy:
    pipx: gixy
  gphotos-sync:
    pipx: gphotos-sync
  gnu:darwin:
    brew:
      - coreutils
      - findutils
      - gawk
      - gnu-getopt
      - gnu-indent
      - gnu-tar
      - gnu-sed
      - gnutls
      - grep
  gtop:
    brew: gtop
    npm: gtop
  gulp:
    brew: gulp
    npm: gulp
  http-prompt:
    brew: http-prompt
    pipx: http-prompt
  httpstat:
    brew: httpstat
    pipx: httpstat
  ideviceinstaller:
    brew:darwin: ideviceinstaller
  imagemagick:
    apk: imagemagick
    apt: imagemagick
    brew: imagemagick
    choco: imagemagick
    dnf: imagemagick
    scoop: imagemagick
  imgur-uploader:
    npm: imgur-uploader-cli
  ionic:
    npm: '@ionic/cli'
  ios-deploy:
    brew:darwin: ios-deploy
    npm:darwin: ios-deploy
  ipfs:
    brew: ipfs
    choco: go-ifps
    nix: ipfs
    port: ipfs
    scoop: go-ipfs
    snap: ipfs
  ipfs-desktop:
    cask: ipfs
    choco: ipfs-desktop
    pacman: ipfs-desktop
    scoop: ipfs-desktop
  ipfs-deploy:
    _bin: ipd
    npm: ipfs-deploy
  is-up:
    npm: is-up-cli
  lazygit:
    brew: lazygit
    choco: lazygit
    go: github.com/jesseduffield/lazygit@latest
    pacman: lazygit
    scoop: lazygit
  libimobiledevice:
    brew:darwin: libimobiledevice
  localtunnel:
    brew: localtunnel
    npm: localtunnel
  mjml:
    cask: mjml
    npm: mjml
  molecule:
    brew: molecule
    pipx: molecule
  nativefier:
    _deps:
      - imagemagick
    npm: nativefier
  ncc:
    brew: ncc
    npm: '@vercel/ncc'
  netcat:
    apt: netcat
    brew: netcat
    choco: netcat
    dnf: netcat
    pacman: netcat
    scoop: netcat
  nb:
    _deps:
      - bat
      - netcat
      - pandoc
      - rg
      - tig
      - w3m
    basher: xwmx/nb
    bpkg: xwmx/nb
    brew: nb
    npm: nb.sh
  nectar:
    npm: nectarjs
  neovim:
    apk: neovim
    apt:
      - neovim
      - python3-neovim
    brew: neovim
    choco: neovim
    dnf:
      - neovim
      - python3-neovim
    flatpak: io.neovim.nvim
    nix: neovim
    pacman:
      - neovim
      - python-pynvim
    pkg:
      - neovim
      - py27-pynvim
      - py36-pynvim
    port: neovim
    winget: Neovim.Neovim
    zypper:
      - neovim
      - python-neovim
      - python3-neovim
  ngxtop:
    pipx: ngxtop
  node:
    brew: node
    scoop: nodejs
  nest:
    npm: '@nestjs/cli'
  newman:
    brew: newman
    npm: newman
  np:
    npm: np
  npm-check:
    npm: npm-check
  oclif:
    npm: oclif
  oh-my-posh:
    brew: jandedobbeleer/oh-my-posh/oh-my-posh
    scoop:
      - clink
      - https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json
  package-size:
    npm: package-size
  pageres:
    npm: pageres-cli
  pandoc:
    _deps:
      - python
    apt: pandoc
    brew:
      - pandoc
      - librsvg
      - homebrew/cask/basictex
    choco:
      - pandoc
      - rsvg-convert
      - miktex
    crew: pandoc
    dnf: pandoc
    nix: pandoc
    pacman: pandoc
    winget: pandoc
  pipx:
    brew: pipx
  pkg:
    npm: pkg
  playwright:
    npm: playwright
  pm2:
    npm: pm2
  pre-commit:
    brew: pre-commit
    pipx: pre-commit
  prettier:
    brew: prettier
    npm: prettier
  psi:
    npm: psi
  python:
    apt: python3-pip
    brew: python
    dnf: python3-pip
    pacman: python-pip
    scoop: python
  pywhat:
    brew: pywhat
    pipx: pywhat
    port: pywhat
  ramda:
    npm: ramda-cli
  ripgrep:
    _bin: rg
    apt: ripgrep
    brew: ripgrep
    cargo: ripgrep
    choco: ripgrep
    dnf: ripgrep
    nix: ripgrep
    pacman: ripgrep
    pkg: ripgrep
    port: ripgrep
    scoop: ripgrep
    zypper: ripgrep
  ripgrep-all:
    _bin: rga
    brew:
      - ffmpeg
      - pandoc
      - poppler
      - rga
      - tesseract
    choco: ripgrep-all
    nix: ripgrep-all
    pacman: ripgrep-all
  rofi:
    apt: rofi
    dnf: rofi
    pacman: rofi
    pkg: rofi
    port: rofi
    zypper: rofi
  rsync:
    apt: rsync
    brew: rsync
    choco: rsync
    dnf: rsync
  sad:
    brew: ms-jpq/sad/sad
    pacman: sad
  secretive:
    cask: secretive
  semantic-release:
    npm: semantic-release
  sentry-cli:
    brew: getsentry/tools/sentry-cli
    npm: '@sentry/cli'
    scoop: sentry-cli
  serve:
    npm: serve
  serverless:
    brew: serverless
    npm: serverless
  share:
    npm: share-cli
  sharp:
    npm: sharp-cli
  shotcut:
    choco: shotcut
    flatpak: org.shotcut.Shotcut
    snap: shotcut
  sloth:
    cask: stats
  social-analyzer:
    brew: social-analyzer
    pipx: social-analyzer
  speed-test:
    npm: speed-test
  spotdl:
    _deps:
      - ffmpeg
    pipx: spotdl
  sshpass:
    apt: sshpass
    brew: hudochenkov/sshpass/sshpass
    dnf: sshpass
  starred:
    pipx: starred
  statcode:
    pipx: statcode
    yay: statcode
  stats:
    cask: stats
  stegcloak:
    npm: stegcloak
  supdock:
    npm: supdock
  surge:
    npm: surge
  svgo:
    brew: svgo
    npm: svgo
  terminalizer:
    npm: terminalizer
  tig:
    brew: tig
    nix: tig
    pkg: tig
  tinypng:
    npm: tinypng-cli
  tldr:
    brew: tldr
    npm: tldr
  trellis:
    brew: roots/tap/trellis-cli
  trufflehog:
    brew: trufflesecurity/trufflehog/trufflehog
  tmux:
    apt: tmux
    brew:
      - awk
      - gnu-sed
      - perl
      - tmux
  tree-sitter:
    cargo: tree-sitter-cli
  ts2c:
    npm: ts2c
  typescript:
    _bin: tsc
    brew: typescript
    npm: tsc
  virtualenv:
    brew: virtualenv
    pipx: virtualenv
  volta:
    brew: volta
    scoop: volta
  w3m:
    apt: w3m
    brew: w3m
    dnf: w3m
    pacman: w3m
    port: w3m
    zypper: w3m
  wget:
    apk: wget
    apt: wget
    brew: rsync
    dnf: wget
    whalebrew: whalebrew/wget
  wifi-password:
    bpkg: rauchg/wifi-password
    brew: wifi-password
    npm: wifi-password-cli
  wordpressify:
    npm: wordpressify
  wrangler:
    npm: '@cloudflare/wrangler'
  yamllint:
    brew: yamllint
    pipx: yamllint
  youtube-dl:
    pipx: youtube-dl
    port: youtube-dl
    brew: youtube-dl
  zx:
    brew: zx
    npm: zx

installerPostInstallScripts:
  astronvim: |
    nvim --headless -c 'autocmd User PackerComplete quitall'
  bottom:
    snap: |
      sudo snap connect bottom:mount-observe
      sudo snap connect bottom:hardware-observe
      sudo snap connect bottom:system-observe
      sudo snap connect bottom:process-control
  gdu:
    brew: brew link --overwrite gdu
    snap: |
      sudo snap connect gdu-disk-usage-analyzer:mount-observe :mount-observe
      sudo snap connect gdu-disk-usage-analyzer:system-backup :system-backup
      sudo snap alias gdu-disk-usage-analyzer.gdu gdu
  git-lfs: git lfs install
  nb: nb completions install
  oh-my-posh:
    scoop: clink autorun install
  pipx:
    brew: pipx ensurepath
  python:
    brew: |
      python3 -m pip install --upgrade setuptools
      python3 -m pip install --upgrade pip
  volta: |
    volta setup
    volta install node@latest

softwarePlugins:
  dotnet:
    plugins:
      - Microsoft.CST.AttackSurfaceAnalyzer.CLI
  vim:
    plugins:
      - https://github.com/dense-analysis/ale.git
      - https://github.com/pearofducks/ansible-vim.git
      - https://github.com/neoclide/coc.nvim.git
      - https://github.com/ekalinin/dockerfile.vim.git
      - https://github.com/editorconfig/editorconfig-vim.git
      - https://github.com/junegunn/fzf.git
      - https://github.com/junegunn/fzf.vim.git
      - https://github.com/itchyny/lightline.vim.git
      - https://github.com/scrooloose/nerdtree.git
      - https://github.com/stanangeloff/php.vim.git
      - https://github.com/hdima/python-syntax.git
      - https://github.com/vim-syntastic/syntastic.git
      - https://github.com/vim-airline/vim-airline.git
      - https://github.com/kristijanhusak/vim-carbon-now-sh.git
      - https://github.com/ryanoasis/vim-devicons.git
      - https://github.com/tpope/vim-fugitive.git
      - https://github.com/airblade/vim-gitgutter.git
      - https://github.com/fatih/vim-go.git
      - https://github.com/pangloss/vim-javascript.git
      - https://github.com/mxw/vim-jsx.git
      - https://github.com/plasticboy/vim-markdown.git
      - https://github.com/terryma/vim-multiple-cursors.git
      - https://github.com/prettier/vim-prettier.git
      - https://github.com/tpope/vim-sensible.git
      - https://github.com/tpope/vim-surround.git
      - https://github.com/nanotee/zoxide.vim.git
  # wget https://gitlab.com/megabyte-labs/gas-station/-/raw/master/environments/prod/group_vars/desktop/vscode-extensions.yml
  # yq e '.vscode_extensions[].name' vscode-extensions.yml
  visualStudioCode:
    plugins:
      - Angular.ng-template
      - attilabuti.vscode-mjml
      - bierner.markdown-emoji
      - ChakrounAnas.turbo-console-log
      - ChFlick.firecode
      - chrmarti.regex
      - cweijan.vscode-mysql-client2
      - DavidAnson.vscode-markdownlint
      - dbaeumer.vscode-eslint
      - denoland.vscode-deno
      - eamodio.gitlens
      - EditorConfig.EditorConfig
      - esbenp.prettier-vscode
      - ericadamski.carbon-now-sh
      - firsttris.vscode-jest-runner
      - formulahendry.auto-rename-tag
      - formulahendry.code-runner
      - GitHub.vscode-pull-request-github
      - GitLab.gitlab-workflow
      - GoogleCloudTools.cloudcode
      - golang.Go
      - HashiCorp.terraform
      - hediet.vscode-drawio
      - IBM.output-colorizer
      - Kelvin.vscode-sshfs
      - mads-hartmann.bash-ide-vscode
      - ms-azuretools.vscode-docker
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - ms-vscode-remote.remote-containers
      - ms-vscode-remote.remote-ssh
      - ms-vscode-remote.remote-wsl
      - ms-python.python
      - ms-vscode.PowerShell
      - MS-vsliveshare.vsliveshare
      - MS-vsliveshare.vsliveshare-audio
      - njpwerner.autodocstring
      - nrwl.angular-console
      - philnash.ngrok-for-vscode
      - PKief.material-icon-theme
      - pranaygp.vscode-css-peek
      - quicktype.quicktype
      - rbbit.typescript-hero
      - redhat.ansible
      - redhat.vscode-yaml
      - richie5um2.vscode-sort-json
      - Rubymaniac.vscode-paste-and-indent
      - salbert.comment-ts
      - shd101wyy.markdown-preview-enhanced
      - softwaredotcom.swdc-vscode
      - steoates.autoimport
      - stylelint.vscode-stylelint
      - timonwong.shellcheck
      - toba.vsfire
      - tyriar.sort-lines
      - usernamehw.errorlens
      - valentjn.vscode-ltex
      - VisualStudioExptTeam.vscodeintellicode
      - vsciot-vscode.vscode-arduino
      - vsls-contrib.codetour
      - vsls-contrib.gistfs
      - wayou.vscode-todo-highlight
      - wix.vscode-import-cost
      - yatki.vscode-surround

# The order which the installer uses to determine which package manager to use while installing
installerPreference:
  - flatpak
  - snap
  - whalebrew
  - apt
  - dnf
  - pacman
  - apk
  - nix
  - pkg
  - zypper
  - brew
  - crew
  - port
  - yay
  - choco
  - scoop
  - winget
  - go
  - cargo
  - npm
  - pipx
  - gem
  - cask
  - bpkg
  - basher
  - appimage
  - binary
