### VIM
{{- $refreshPeriod := "140h" }}
{{- $vimPlugins := .plugins.vim }}
{{- range $vimPlugin := $vimPlugins }}
{{-   $folderName :=  trimSuffix ".git" (last (splitList "/" $vimPlugin)) }}
[".vim/plugged/{{ $folderName }}"]
    type = "git-repo"
    url = "{{ $vimPlugin }}"
    refreshPeriod = "{{ $refreshPeriod }}"
    [".vim/plugged/{{ $folderName }}".pull]
        args = ["--ff-only"]
{{- end }}

### Shell
[".config/shell/lscolors.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/lscolors.sh"
    refreshPeriod = "{{ $refreshPeriod }}"
[".local/antigen.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/zsh-users/antigen/develop/bin/antigen.zsh"
    refreshPeriod = "{{ $refreshPeriod }}"
[".local/docker-functions.bash"]
    type = "file"
    url = "https://raw.githubusercontent.com/jessfraz/dotfiles/master/.dockerfunc"
    refreshPeriod = "{{ $refreshPeriod }}"
[".local/fzf-git.bash"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/fzf-git.sh/main/fzf-git.sh"
    refreshPeriod = "{{ $refreshPeriod }}"
[".local/fzf-tmux.bash"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-tmux"
    refreshPeriod = "{{ $refreshPeriod }}"
[".local/share/delta/themes.gitconfig"]
    type = "file"
    url = "https://raw.githubusercontent.com/dandavison/delta/master/themes.gitconfig"
    refreshPeriod = "{{ $refreshPeriod }}"
[".local/share/zsh/site-functions/fzf.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh"
    refreshPeriod = "{{ $refreshPeriod }}"
[".local/share/zsh/site-functions/fzf-key-bindings.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh"
    refreshPeriod = "{{ $refreshPeriod }}"

### Neovim
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/AstroNvim/AstroNvim.git"
    refreshPeriod = "{{ $refreshPeriod }}"
    [".config/nvim".pull]
        args = ["--ff-only"]

{{- if not .host.headless }}
### Hack Nerd Font Download
{{-   $refreshPeriod := "4800h" }}
{{-   $fontDir := "" }}
{{-   $fontUrlBase := "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack"}}
{{-   if eq .host.distro.family "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{-   else if eq .host.distro.family "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{-   else if eq .host.distro.family "windows" }}
{{-     $fontDir = "Windows/Fonts" }}
{{-   end }}
["{{ $fontDir }}/Hack-Regular-Nerd-Font.ttf"]
    type = "file"
    url = "{{ $fontUrlBase }}/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete{{if eq .host.distro.family "windows"}}%20Windows%20Compatible{{end}}.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
["{{ $fontDir }}/Hack-Bold-Nerd-Font.ttf"]
    type = "file"
    url = "{{ $fontUrlBase }}/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete{{if eq .host.distro.family "windows"}}%20Windows%20Compatible{{end}}.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
["{{ $fontDir }}/Hack-Italic-Nerd-Font.ttf"]
    type = "file"
    url = "{{ $fontUrlBase }}/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete{{if eq .host.distro.family "windows"}}%20Windows%20Compatible{{end}}.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
["{{ $fontDir }}/Hack-Bold-Italic-Nerd-Font.ttf"]
    type = "file"
    url = "{{ $fontUrlBase }}/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete{{if eq .host.distro.family "windows"}}%20Windows%20Compatible{{end}}.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"

### Montserrat Font Download
{{-   $fontUrlBase := "https://github.com/JulietaUla/Montserrat/raw/master/fonts/ttf/Montserrat-"}}
{{-   $fonts := list "Black" "BlackItalic" "Bold" "BoldItalic" "ExtraBold" "ExtraBoldItalic" "ExtraLight" "ExtraLightItalic" "Italic" "Light" "LightItalic" "Medium" "MediumItalic" "Regular" "SemiBold" "SemiBoldItalic" "Thin" "ThinItalic" }}
{{-   range $font := $fonts }}
["{{ $fontDir }}/Montserrat-{{ $font }}.ttf"]
    type = "file"
    url = "{{ $fontUrlBase }}{{ $font }}.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
{{-   end }}

### ZillaSlab Font Download
{{-   $fontUrlBase := "https://github.com/typotheque/zilla-slab/raw/master/fonts_TTF/ZillaSlab"}}
{{-   $fonts := list "-Bold" "-BoldItalic" "-Italic" "-Light" "-LightItalic" "-Medium" "-MediumItalic" "-Regular" "-SemiBold" "-SemiBoldItalic" "Highlight-Bold" "Highlight-Regular" }}
{{-   range $font := $fonts }}
["{{ $fontDir }}/ZillaSlab{{ $font }}.ttf"]
    type = "file"
    url = "{{ $fontUrlBase }}{{ $font }}.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
{{-   end }}

### Miscellaneous Fonts Download
["{{ $fontDir }}/FontAwesome.ttf"]
    type = "file"
    # Source URL
    # url = "https://github.com/VermiumSifell/dotfiles/raw/main/dot_local/share/fonts/fontawesome.ttf"
    url = "https://gitlab.com/megabyte-labs/misc/dotfiles/-/raw/master/dotfiles/.local/share/chezmoi/dot_local/share/fonts/FontAwesome.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
["{{ $fontDir }}/Weather-Icons.ttf"]
    type = "file"
    # Source URL
    # url = "https://github.com/VermiumSifell/dotfiles/raw/main/dot_local/share/fonts/weathericons.ttf"
    url = "https://gitlab.com/megabyte-labs/misc/dotfiles/-/raw/master/dotfiles/.local/share/chezmoi/dot_local/share/fonts/Weather-Icons.ttf"
    refreshPeriod = "{{ $refreshPeriod }}"
{{- end }}
