[".vim/plugged/ale"]
    type = "git-repo"
    url = "https://github.com/dense-analysis/ale.git"
    refreshPeriod = "140h"
    [".vim/plugged/ale".pull]
        args = ["--ff-only"]
[".vim/plugged/ale"]
    type = "git-repo"
    url = "https://github.com/pearofducks/ansible-vim.git"
    refreshPeriod = "140h"
    [".vim/plugged/ale".pull]
        args = ["--ff-only"]
[".vim/plugged/ale"]
    type = "git-repo"
    url = "https://github.com/dense-analysis/ale.git"
    refreshPeriod = "140h"
    [".vim/plugged/ale".pull]
        args = ["--ff-only"]
[".vim/plugged/ale"]
    type = "git-repo"
    url = "https://github.com/dense-analysis/ale.git"
    refreshPeriod = "140h"
    [".vim/plugged/ale".pull]
        args = ["--ff-only"]
[".vim/plugged/ale"]
    type = "git-repo"
    url = "https://github.com/dense-analysis/ale.git"
    refreshPeriod = "140h"
    [".vim/plugged/ale".pull]
        args = ["--ff-only"]



https://github.com/pearofducks/ansible-vim.git
https://github.com/neoclide/coc.nvim.git
https://github.com/ekalinin/dockerfile.vim.git
https://github.com/editorconfig/editorconfig-vim.git
https://github.com/junegunn/fzf.git
https://github.com/junegunn/fzf.vim.git
https://github.com/itchyny/lightline.vim.git
https://github.com/scrooloose/nerdtree.git
https://github.com/stanangeloff/php.vim.git
https://github.com/hdima/python-syntax.git
https://github.com/vim-syntastic/syntastic.git
https://github.com/vim-airline/vim-airline.git
https://github.com/kristijanhusak/vim-carbon-now-sh.git
https://github.com/ryanoasis/vim-devicons.git
https://github.com/tpope/vim-fugitive.git
https://github.com/airblade/vim-gitgutter.git
https://github.com/fatih/vim-go.git
https://github.com/pangloss/vim-javascript.git
https://github.com/mxw/vim-jsx.git
https://github.com/plasticboy/vim-markdown.git
https://github.com/terryma/vim-multiple-cursors.git
https://github.com/prettier/vim-prettier.git
https://github.com/tpope/vim-sensible.git
https://github.com/tpope/vim-surround.git
https://github.com/nanotee/zoxide.vim.git