{{- $refreshPeriod := "140h" }}
{{-}}
[".vim/plugged/ale"]
    type = "git-repo"
    url = "https://github.com/dense-analysis/ale.git"
    refreshPeriod = "{{ $refreshPeriod }}"
    [".vim/plugged/ale".pull]
        args = ["--ff-only"]
[".vim/plugged/ale"]
    type = "git-repo"
    url = "https://github.com/pearofducks/ansible-vim.git"
    refreshPeriod = "140h"
    [".vim/plugged/ale".pull]
        args = ["--ff-only"]
[".vim/plugged/ale"]
    type = "git-repo"
    url = "https://github.com/dense-analysis/ale.git"
    refreshPeriod = "140h"
    [".vim/plugged/ale".pull]
        args = ["--ff-only"]
[".vim/plugged/ale"]
    type = "git-repo"
    url = "https://github.com/dense-analysis/ale.git"
    refreshPeriod = "140h"
    [".vim/plugged/ale".pull]
        args = ["--ff-only"]
[".vim/plugged/ale"]
    type = "git-repo"
    url = "https://github.com/dense-analysis/ale.git"
    refreshPeriod = "140h"
    [".vim/plugged/ale".pull]
        args = ["--ff-only"]

### Hack Nerd Font Download
{{- if not .host.headless }}

{{-   $fontDir := "" }}
{{-   $fontUrlBase := "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack"}}
{{-   if eq .host.distro.family "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{-   else if eq .host.distro.family "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{-   else if eq .host.distro.family "windows" }}
{{-     $fontDir = "Windows/Fonts" }}
{{-   end }}

["{{ $fontDir }}/Hack-Regular-Nerd-Font.ttf"]
    type = "file"
{{- if eq .host.distro.family "windows" }}
    url = "{{ $fontUrlBase }}/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf"
{{- else }}
    url = "{{ $fontUrlBase }}/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf"
{{- end }}
    refreshPeriod = "{{ $refreshPeriod }}"

["{{ $fontDir }}/Hack-Bold-Nerd-Font.ttf"]
    type = "file"
{{- if eq .host.distro.family "windows" }}
    url = "{{ $fontUrlBase }}/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf"
{{- else }}
    url = "{{ $fontUrlBase }}/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete.ttf"
{{- end }}
    refreshPeriod = "{{ $refreshPeriod }}"

["{{ $fontDir }}/Hack-Italic-Nerd-Font.ttf"]
    type = "file"
{{- if eq .host.distro.family "windows" }}
    url = "{{ $fontUrlBase }}/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf"
{{- else }}
    url = "{{ $fontUrlBase }}/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete.ttf"
{{- end }}
    refreshPeriod = "{{ $refreshPeriod }}"

["{{ $fontDir }}/Hack-Bold-Italic-Nerd-Font.ttf"]
    type = "file"
{{- if eq .host.distro.family "windows" }}
    url = "{{ $fontUrlBase }}/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf"
{{- else }}
    url = "{{ $fontUrlBase }}/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete.ttf"
{{- end }}
    refreshPeriod = "{{ $refreshPeriod }}"

### ZillaSlab Font Download
{{-   $fontUrlBase := "https://github.com/typotheque/zilla-slab/raw/master/fonts_TTF"}}
{{-   $fonts := list "ZillaSlab-Bold.ttf" "ZillaSlab-BoldItalic.ttf" "ZillaSlab-Italic.ttf" "ZillaSlab-Light.ttf" "ZillaSlab-LightItalic.ttf" "ZillaSlab-Medium.ttf" "ZillaSlab-MediumItalic.ttf" "ZillaSlab-Regular.ttf" "ZillaSlab-SemiBold.ttf" "ZillaSlab-SemiBoldItalic.ttf" "ZillaSlabHighlight-Bold.ttf" "ZillaSlabHighlight-Regular.ttf" }}
{{-   range $font := $fonts }}
["{{ $fontDir }}/{{ $font }}"]
    type = "file"
    url = "{{ $fontUrlBase }}/{{ $font }}"
    refreshPeriod = "{{ $refreshPeriod }}"
{{-   end }}
{{- end }}