---
preference:
  - flatpak
  - snap
  - whalebrew
  - apt
  - dnf
  - pacman
  - apk
  - nix
  - pkg
  - zypper
  - brew
  - port
  - yay
  - choco
  - scoop
  - winget
  - go
  - cargo
  - npm
  - pipx
  - gem
  - cask
  - appimage
  - binary

alternatives:
  altair:
    cask: altair-graphql-client
    choco: altair-graphql
    snap: altair
    yay: altair
  astronvim:
    _deps:
      - bottom
      - gdu
      - lazygit
      - neovim
      - node
      - python
      - ripgrep
      - tree-sitter-cli
  delta:
    brew: git-delta
    scoop: delta
  bash-completion:
    brew: bash-completion
  bottom:
    brew: bottom
    pacman: bottom
    scoop: bottom
    snap: bottom
  bw:
    choco: bitwarden-cli
    snap: bw
  gdu:
    brew: gdu
    go: github.com/dundee/gdu/v5/cmd/gdu@latest
    pacman: gdu
    snap: gdu-disk-usage-analyzer
  gdu:debian:
    apt: gdu
  git:
    apk: git
    apt: git
    brew: git
    dnf: git
  git-lfs:
    _deps:
      - git
    brew: git-lfs
    scoop: git-lfs
  gnu:
    brew:
      - coreutils
      - findutils
      - gawk
      - gnu-getopt
      - gnu-indent
      - gnu-tar
      - gnu-sed
      - gnutls
      - grep
  lazygit:
    brew: lazygit
    choco: lazygit
    go: github.com/jesseduffield/lazygit@latest
    pacman: lazygit
    scoop: lazygit
  nb:
    brew: nb
  # :debian is defined so nothing will be installed on Debian for nb
  nb:debian:
    brew: []
  neovim:
    apk: neovim
    apt:
      - neovim
      - python3-neovim
    brew: neovim
    choco: neovim
    dnf:
      - neovim
      - python3-neovim
    flatpak: io.neovim.nvim
    nix: neovim
    pacman:
      - neovim
      - python-pynvim
    pkg:
      - neovim
      - py27-pynvim
      - py36-pynvim
    port: neovim
    winget: Neovim.Neovim
    zypper:
      - neovim
      - python-neovim
      - python3-neovim
  node:
    brew: node
    scoop: nodejs
  oh-my-posh:
    brew: jandedobbeleer/oh-my-posh/oh-my-posh
    scoop:
      - clink
      - https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json
  pipx:
    brew: pipx
  python:
    apt: python3-pip
    brew: python
    dnf: python3-pip
    pacman: python-pip
    scoop: python
  ripgrep:
    apt: ripgrep
    brew: ripgrep
    cargo: ripgrep
    choco: ripgrep
    dnf: ripgrep
    nix: ripgrep
    pacman: ripgrep
    pkg: ripgrep
    port: ripgrep
    scoop: ripgrep
    zypper: ripgrep
  ripgrep-all:
    brew:
      - ffmpeg
      - pandoc
      - poppler
      - rga
      - tesseract
    choco: ripgrep-all
    nix: ripgrep-all
    pacman: ripgrep-all
  rofi:
    apt: rofi
    dnf: rofi
    pacman: rofi
    pkg: rofi
    port: rofi
    zypper: rofi
  rsync:
    apt: rsync
    brew: rsync
    choco: rsync
    dnf: rsync
  sad:
    brew: ms-jpq/sad/sad
    pacman: sad
  shotcut:
    choco: shotcut
    flatpak: org.shotcut.Shotcut
    snap: shotcut
  tmux:
    brew:
      - awk
      - gnu-sed
      - perl
      - tmux
  tree-sitter-cli:
    cargo: tree-sitter-cli
  volta:
    brew: volta
    scoop: volta
  wget:
    apk: wget
    apt: wget
    brew: rsync
    dnf: wget
    whalebrew: whalebrew/wget

postinstall:
  astronvim: |
    nvim --headless -c 'autocmd User PackerComplete quitall'
  bottom:
    snap: |
      sudo snap connect bottom:mount-observe
      sudo snap connect bottom:hardware-observe
      sudo snap connect bottom:system-observe
      sudo snap connect bottom:process-control
  gdu:
    brew: brew link --overwrite gdu
    snap: |
      sudo snap connect gdu-disk-usage-analyzer:mount-observe :mount-observe
      sudo snap connect gdu-disk-usage-analyzer:system-backup :system-backup
      sudo snap alias gdu-disk-usage-analyzer.gdu gdu
  git-lfs: git lfs install
  nb: nb completions install
  oh-my-posh:
    scoop: clink autorun install
  pipx:
    brew: pipx ensurepath
  python:
    brew: |
      python3 -m pip install --upgrade setuptools
      python3 -m pip install --upgrade pip
  volta: |
    volta setup
    volta install node@latest

plugins:
  vim:
    - https://github.com/dense-analysis/ale.git
    - https://github.com/pearofducks/ansible-vim.git
    - https://github.com/neoclide/coc.nvim.git
    - https://github.com/ekalinin/dockerfile.vim.git
    - https://github.com/editorconfig/editorconfig-vim.git
    - https://github.com/junegunn/fzf.git
    - https://github.com/junegunn/fzf.vim.git
    - https://github.com/itchyny/lightline.vim.git
    - https://github.com/scrooloose/nerdtree.git
    - https://github.com/stanangeloff/php.vim.git
    - https://github.com/hdima/python-syntax.git
    - https://github.com/vim-syntastic/syntastic.git
    - https://github.com/vim-airline/vim-airline.git
    - https://github.com/kristijanhusak/vim-carbon-now-sh.git
    - https://github.com/ryanoasis/vim-devicons.git
    - https://github.com/tpope/vim-fugitive.git
    - https://github.com/airblade/vim-gitgutter.git
    - https://github.com/fatih/vim-go.git
    - https://github.com/pangloss/vim-javascript.git
    - https://github.com/mxw/vim-jsx.git
    - https://github.com/plasticboy/vim-markdown.git
    - https://github.com/terryma/vim-multiple-cursors.git
    - https://github.com/prettier/vim-prettier.git
    - https://github.com/tpope/vim-sensible.git
    - https://github.com/tpope/vim-surround.git
    - https://github.com/nanotee/zoxide.vim.git
