---
preference:
  - flatpak
  - snap
  - whalebrew
  - apt
  - dnf
  - pacman
  - apk
  - brew
  - yay
  - choco
  - scoop
  - winget
  - cask
  - go
  - cargo
  - binary

alternatives:
  delta:
    brew:
      - git-delta
      - example-dependency
    scoop: delta
  git:
    apk: git
    apt: git
    brew: git
    dnf: git
  git-lfs:
    brew: git-lfs
    scoop: git-lfs
  nb:
    brew: nb
  # :debian is defined so nothing will be installed on Debian for nb
  nb:debian:
    brew: []
  rsync:
    apt: rsync
    brew: rsync
    choco: rsync
    dnf: rsync
  shotcut:
    choco: shotcut
    flatpak: org.shotcut.Shotcut
    snap: shotcut
  volta:
    brew: volta
    scoop: volta
  wget:
    apk: wget
    apt: wget
    brew: rsync
    dnf: wget
    whalebrew: whalebrew/wget

dependencies:
  git-lfs:
    - git

preinstall:
  example-package: |
    echo "preinstall routine"

postinstall:
  git-lfs: |
    git lfs install
  git-lfs:darwin: |
    echo ":darwin is defined so this step will be used on Darwin with PowerShell"
  git-lfs:windows: |
    echo ":windows is defined so this step will be used on Windows with PowerShell"
  nb: |
    nb completions install
  volta: |
    volta setup
    volta install node@latest

plugins:
  vim:
    - https://github.com/dense-analysis/ale.git
    - https://github.com/pearofducks/ansible-vim.git
    - https://github.com/neoclide/coc.nvim.git
    - https://github.com/ekalinin/dockerfile.vim.git
    - https://github.com/editorconfig/editorconfig-vim.git
    - https://github.com/junegunn/fzf.git
    - https://github.com/junegunn/fzf.vim.git
    - https://github.com/itchyny/lightline.vim.git
    - https://github.com/scrooloose/nerdtree.git
    - https://github.com/stanangeloff/php.vim.git
    - https://github.com/hdima/python-syntax.git
    - https://github.com/vim-syntastic/syntastic.git
    - https://github.com/vim-airline/vim-airline.git
    - https://github.com/kristijanhusak/vim-carbon-now-sh.git
    - https://github.com/ryanoasis/vim-devicons.git
    - https://github.com/tpope/vim-fugitive.git
    - https://github.com/airblade/vim-gitgutter.git
    - https://github.com/fatih/vim-go.git
    - https://github.com/pangloss/vim-javascript.git
    - https://github.com/mxw/vim-jsx.git
    - https://github.com/plasticboy/vim-markdown.git
    - https://github.com/terryma/vim-multiple-cursors.git
    - https://github.com/prettier/vim-prettier.git
    - https://github.com/tpope/vim-sensible.git
    - https://github.com/tpope/vim-surround.git
    - https://github.com/nanotee/zoxide.vim.git
