display-name = "Paul DURANT"
downloads-dir = "~/Downloads"
signature = "Cordialement,\nPaul DURANT"
email-listing-page-size = 50

[gmail]
default = true
email = "p.durant@gmail.com"

backend = "imap"
imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "p.durant@gmail.com"
imap-passwd-cmd = "pass show gmail"

sender = "smtp"
smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "p.durant@gmail.com"
smtp-passwd-cmd = "pass show gmail"

[gmail.folder-aliases]
sent = "[Gmail]/Sent Mail"
drafts = "[Gmail]/Drafts"

[outlook]
email = "pdurant@outlook.com"
email-listing-page-size = 25
signature = """
Regards,
Paul DURANT
Sent from Outlook
"""

sender = "sendmail"
sendmail-cmd = "/usr/bin/msmtp"

backend = "imap"
imap-host = "outlook.office365.com"
imap-port = 993
imap-login = "pdurant@outlook.com"
imap-passwd-cmd = "security find-internet-password -gs outlook -w"

[posteo-local]
email = "paul.durant@localhost"
display-name = "Paul D."
downloads-dir = "~/Downloads/posteo"

backend = "maildir"
maildir-root-dir = "~/Maildir"

sender = "smtp"
smtp-host = "posteo.de"
smtp-port = 465
smtp-login = "paul.durant@posteo.com"
smtp-passwd-cmd = "security find-internet-password -gs posteo -w"

[posteo-local.mailboxes]
sent = "Sent" # points to ~/Maildir/.Sent
drafts = "~/Maildir/custom/drafts"